default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kane_development

test:
  <<: *default
  database: kane_test

production:
  <<: *default
  database: kane_production
  username: kane
  password: <%= ENV['KANE_DATABASE_PASSWORD'] %>
